#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the unfy network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x98,0x2a,0x8e,0xb5,0x05,0xb8,
    0x01,0x04,0xa4,0x5c,0xdd,0xb8,0x05,0xb8,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x98,0x2a,0x8e,0x0b,0x05,0xb8,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
